apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    deploy: pvc-k8
  name: pvc-k8-gp3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3
