apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pvc-consumer-pod-st1
  name: pvc-consumer-pod-st1
spec:
  containers:
  - image: alpine
    name: pvc-consumer-pod
    command: ["sh", "-c", "echo 'Hello from PVC' > /data/hello.txt && sleep 4d"]
    volumeMounts:
    - mountPath: /data
      name: pvc-storage
    resources: {}
  volumes:
  - name: pvc-storage
    persistentVolumeClaim:
      claimName: pvc-st1
  dnsPolicy: ClusterFirst
  restartPolicy:
