apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-cluster-role
subjects:
- kind: ServiceAccount
  name: metric-aggregation-sa
  namespace: default
